### PR TITLE
Fix identifierRegex failing because of Steam adding https

### PR DESCRIPTION
**Pull request by waylaidwanderer**
Also updates the `options.providerURL` and the test case to match.

### CODE REVIEW

**Comment by waylaidwanderer** [comment]
@Kondax already added a commit for that

**Comment by Kondax** [comment]
Yeah, didn't show on mobile for some reason.

**Comment by switz** [comment]
lmao did we all just freak out about the same thing?

@waylaidwanderer @Kondax @prih @tuktan

what sites do you guys run?

**Comment by prih** [comment]
@switz we are developing the engine, many use it ;)

**Comment by prih** [comment]
@switz case-drop engine

**Comment by meepen** [comment]
love how steam gives us zero notice of any changes to the steam api, sorry for making a duplicate pr, didn't see this one

**Comment by HoffiPL** [comment]
Holly dolly

**Comment by prih** [comment]
they almost every Thursday get drunk and think about what to improve... only such an explanation

**Comment by joshverd** [comment]
Well that answers that. Spent the past hour and a half trying to find out why passport suddenly started spewing errors. 

Classic valve with absolutely no communication.

**Comment by notgne2** [comment]
damn steam, godspeed lads

**Comment by mnzt** [comment]
Hey guys, thank you all for opening issues - I woke up to a barrage of notifications, and clearly something had changed upstream.

Thanks @waylaidwanderer for issuing this PR. I, and I'm sure many others, appreciate it.

**Comment by mnzt** [comment]
I'll be getting this tagged and released to NPM in due course

**Comment by mnzt** [comment]
`passport-steam@1.0.9` is now available with this fix in. Once again - thank you for your contribution.

**Comment by joshverd** [comment]
Thanks so much guys!

**Comment by coooool123** [comment]
Still isn't working for me guys...

**Comment by scholtzm** [comment]
I quickly checked the docs to see if they updated them with this breaking change and indeed they have: https://steamcommunity.com/dev

What a nice surprise from them. 😄

**Comment by coooool123** [comment]
Still isn't working for me - I had even updated the passport-steam to the newest version yet i'm still unable to be redirected back to the site, why can't anyone help me...

**Comment by mnzt** [comment]
@coooool123 Please open an issue and actually provide information to allow us to help you.

**Pull request merged**
