### PR TITLE
Set up for official release of v1.0.0

### PR DESCRIPTION
**Pull request by mnzt**
As discussed in #23.

### CODE REVIEW

**Comment by mnzt** [comment]
Getting some real weird issues with trying to resolve the conflicts. Will try to fix these.

**Comment by welps** [comment]
Hey @mnzt , do you need help resolving this?

**Comment by mnzt** [comment]
@welps I lost all the code in the directory, and am having some real bad issues in terms of machine integrity. If you feel comfortable, would you mind finishing this up?

**Comment by welps** [comment]
No problem dude, I'll take care of it tonight after work.

**Comment by mnzt** [comment]
:+1: I really do believe we should publish this to v1.0.0 and follow semvar. However, publishing this as v1.0.0 kind of goes against semvar, due to their being no breaking changes. Thoughts?

**Comment by welps** [comment]
We can just publish as v1.0.0 to indicate it's ready for production use and then maintain semvar again moving forward. Personally I have no opinion as long as we're consistent after this release.

**Pull request merged**
