### PR TITLE
Update the basic example so it continues to work out of the box

### PR DESCRIPTION
**Pull request by welps**
Hi,

I've made updates to the basic example so it continues to work out of the box. 

I've streamlined the views and routes to make the usage examples more clearly defined. The homepage now welcomes the user and shows the login link if they're not authenticated. When authenticated, they will see their Steam name displayed. 

Regardless of whether they're logged in, a link to see Account Information will be visible on the homepage. If they're not logged in, they'll get dropped back to the homepage otherwise it'll display their Steam avatar image, ID, and name.

Let me know if you have any questions. Thanks.

### CODE REVIEW

**Comment by mnzt** [comment]
👍 

However, I'd suggest storing `apiKey` in a constant at the top, hints towards better future maintenance. Other than that, good work!

**Comment by pronebird** [comment]
:+1:

**Comment by pgrodrigues** [comment]
:+1:

**Comment by 2c2c** [comment]
using this leads to me running into #10 .

**Comment by welps** [comment]
@liamcurry Is there anything I can do to get this pushed through? I think it'd be really helpful for beginners.

**Comment by liamcurry** [comment]
Sorry @welps for the delay. I don't use this module (or even passport) so this repo tends to get neglected. Thanks.

**Comment by mnzt** [comment]
@liamcurry thanks for merging this. Do you have any plans on adding any others who actively use  this package to the approved contributors, so the package can continue development?

**Comment by liamcurry** [comment]
@mnzt I'd be happy to. I can add you and @welps as contributors for now, let me know if there's anyone else I should add.

**Pull request merged**
